# Generated by Django 5.0.4 on 2024-04-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_company_company_id_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(error_messages={'unique': 'This id already exists.'}, max_length=30, primary_key=True, serialize=False),
        ),
    ]
